export const DATA = {
  handle: 'toretto.dev',
  studio: 'Toretto Studios',
  role: 'FiveM Developer',
  years: 5,
  tagline: 'Custom Lua, React NUI, and servers that don\'t fall over at 300 players.',
  about: [
    'I\'m Toretto — a FiveM developer with 5+ years building custom scripts, React-based NUI, and framework-agnostic infrastructure.',
    'Before I was writing exports for clients, I was running Morocco\'s top-rated roleplay server — 300+ concurrent players, nightly. That\'s the lens I write code through: it has to survive peak load, not just pass a demo.',
    'Fluent in English, French, Arabic, and Spanish. I work with server owners worldwide — async when you need it, same-timezone when you don\'t.',
  ],
  stats: [
    { k: 'years shipping', v: '5+' },
    { k: 'peak concurrents', v: '300+' },
    { k: 'frameworks', v: '8' },
    { k: '5★ reviews', v: '∞' },
  ],
  frameworks: [
    { name: 'QBOX',       kind: 'core',       url: 'https://qbox.re',                                     icon: '/assets/frameworks/qbox.webp' },
    { name: 'QBCore',     kind: 'core',       url: 'https://qbox.re',                                     icon: '/assets/frameworks/qbcore.webp' },
    { name: 'ESX',        kind: 'core',       url: 'https://esx-framework.org',                           icon: '/assets/frameworks/esx.webp' },
    { name: 'vRP',        kind: 'legacy',     url: 'https://github.com/vRP-framework/vRP',                icon: '/assets/frameworks/vrp.webp' },
    { name: 'OX Core',    kind: 'core',       url: 'https://overextended.dev/ox_core',                    icon: '/assets/frameworks/oxcore.webp' },
    { name: 'ND Core',    kind: 'core',       url: 'https://ndcore.dev',                                  icon: '/assets/frameworks/ndcore.webp' },
    { name: 'Standalone', kind: 'standalone', url: 'https://fivem.net',                                   icon: '/assets/frameworks/fivemlogo.webp' },
    { name: 'Custom',     kind: 'custom',     url: '#',                                                   icon: '/assets/frameworks/customframework.webp' },
  ],
  services: [
    {
      code: 'SVC-01',
      title: 'Custom Scripts',
      body: 'Bespoke Lua resources built to your spec. Clean exports, proper events, zero spaghetti. Ships with README, config, and the edge-cases already handled.',
      bullets: ['QBOX / QBCore / ESX / OX Core / standalone', 'ox_lib + oxmysql first-class', 'Performance budgeted under 0.02ms idle'],
    },
    {
      code: 'SVC-02',
      title: 'Server Development',
      body: 'End-to-end server setup: framework selection, database, whitelisting, anti-cheat, moderation tooling, launch hardening. Comes with docs and a runbook.',
      bullets: ['Framework migration & upgrades', 'txAdmin / discord integrations', 'Launch-day incident support'],
    },
    {
      code: 'SVC-03',
      title: 'Bug Fixes & Optimization',
      body: 'Triage existing servers pinned to the floor by a bad resource. Profile, patch, ship. Usually under a week, often under a day.',
      bullets: ['resmon + profiler audits', 'Tick/thread cleanup', 'Memory leak hunting'],
    },
    {
      code: 'SVC-04',
      title: 'UI / NUI Development',
      body: 'React + TypeScript NUI that doesn\'t feel like a 2015 HUD. Accessible, animated, integrated with your existing resources.',
      bullets: ['React + TS + Tailwind / CSS modules', 'Designed alongside the script', 'Works on 1366 through 4K'],
    },
  ],
  projects: [
    {
      id: 'trt_jobvehicles',
      kind: 'resource',
      version: '1.2.0',
      framework: 'QBOX',
      blurb: 'Job vehicle system. Players with the right job+rank can create and spawn owned vehicles from designated locations — without ever touching SQL directly (which is bad practice and breaks under load).',
      size: '84 KB',
      deps: ['ox_lib', 'oxmysql'],
      stars: 34,
      url: 'https://github.com/t0r3tto/trt_jobvehicles',
      type: 'Open source',
    },
    {
      id: 'trt_lockdown',
      kind: 'resource',
      version: '1.0.1',
      framework: 'QBOX',
      blurb: 'Time-windowed server access control. During lockdown, only whitelisted players connect. Ideal for scheduled events, beta phases, or staff-only windows.',
      size: '22 KB',
      deps: ['ox_lib'],
      stars: 18,
      url: 'https://github.com/t0r3tto/trt_lockdown',
      type: 'Open source',
    },
    {
      id: 'trt_fetchInventory',
      kind: 'resource',
      version: '2.1.0',
      framework: 'QBCore / ESX / QBOX',
      blurb: 'Manage offline inventories, stashes, and trunks. Open and edit any inventory in your DB through a single in-game command. Ships across three frameworks.',
      size: '156 KB',
      deps: ['ox_inventory'],
      stars: null,
      url: 'https://toretto.tebex.io/package/6212695',
      type: 'Paid — Tebex',
    },
  ],
  reviews: [
    { name: 'death102',          country: 'Denmark',       flag: 'DK', service: 'Custom Script',   price: '$1,000 – $1,500', tier: 'XL', quote: 'Development skills are top-notch. Everything runs smoothly with no bugs, clean and well-structured code. Polite, professional, and done before agreed time. Highly recommend.' },
    { name: 'ghiwunashek',       country: 'Saudi Arabia',  flag: 'SA', service: 'Custom Script',   price: '$500 – $1,000',   tier: 'L',  quote: 'Went above and beyond. Clear communication, fast delivery, top-tier scripting quality. Best in the world.' },
    { name: 'damian_labestia',   country: 'United States', flag: 'US', service: 'Server Creation', price: '$200 – $400',     tier: 'M',  quote: 'Fully delivered on time and the server runs smooth. Definitely hiring him again.' },
    { name: 'drnemanicouagan',   country: 'Canada',        flag: 'CA', service: 'Server Creation', price: '$200 – $400',     tier: 'M',  quote: 'If you want a server, this is the guy. I tried three others before him. Professional.' },
    { name: 'paintmediallc',     country: 'United States', flag: 'US', service: 'Bug Fixing',      price: '$100 – $200',     tier: 'S',  quote: 'I was worried about reaching out — I\'d been scammed before — but he over-delivered on his promise. The most honest person in the game.' },
    { name: 'ashemberlove530',   country: 'United States', flag: 'US', service: 'Bug Fixing',      price: '$100 – $200',     tier: 'S',  quote: 'Outstanding choice. Expertise in delivering bug-free, professional work made collaborating seamless. Quick and cooperative.' },
    { name: 'brothersblood22',   country: 'United States', flag: 'US', service: 'Bug Fixing',      price: '$100 – $200',     tier: 'S',  quote: 'Great to work with, quick with the order. Would love to order from them again.' },
    { name: 'kjeldveldhui588',   country: 'Netherlands',   flag: 'NL', service: 'Bug Fixing',      price: '$50 – $100',      tier: 'XS', quote: 'Amazing work. Really fast response and solid scripting knowledge even on a script he hadn\'t seen before.' },
  ],
  links: [
    { label: 'Store',           handle: 'store.toretto.dev',              href: 'https://store.toretto.dev' },
    { label: 'Discord server',  handle: 'discord.gg/QFCG2kDkeS',          href: 'https://discord.gg/QFCG2kDkeS' },
    { label: 'Discord profile', handle: 'torettooo',                      href: 'https://discord.com/users/294990611633799180' },
    { label: 'GitHub',          handle: 'github.com/t0r3tto',             href: 'https://github.com/t0r3tto' },
  ],
} as const
